### ISSUE TITLE
Make some functions static

### ISSUE THREAD

**Issue by lkotipal** [fmihpc/fsgrid#17]
Right now `calcLocalStart`, `calcLocalSize` and `computeDomainDecomposition` are functions of `FsGrid` objects. They do not however use member variables and only require their parameters. 

Making these functions static would allow using them without instantiating an `FsGrid`-object. This would be useful in `readfields`-functions where the data isn't copied to a new grid but rather just read into a buffer. It would also make the syntax in `ioread.cpp` more logical; there the functions are used to calculate the decomposition and sizes of the _read_ grid instead of the _target_ grid through which the functions are called.

**Comment by ursg** [comment]
Oh indeed, I never considered this. Indeed, this sounds like a good idea.

I guess this then needs a bit of a coordinated code change in vlasiator, as changing them makes the API incompatible?

**Comment by lkotipal** [comment]
Looking at this further the syntax for calling static functions on template classes is a bit annoying and the functions don't seem to care about the typename or stencil width anyway. Should they be moved entirely outside the class?

**Comment by kstppd** [comment]
I am also in doubt about this. We can proceed with having those as static member functions but I really do not like the way they get called, @ursg @lkotipal  . I am leaning more towards either having them outside the fsgrid and possibly encapsulating into a namespace.  I have already converted a few stuff like ioread and vlsvdiff but I do not want to keep going until we decide on this. So what do you think?

**Comment by kstppd** [comment]
Or possibly a new struct that offers those static routines for fsgrid to inherit? Although I am voting for keeping them outside of fsgrid

**Comment by ursg** [comment]
Fixed through pull request #18.
